name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: teatimeguest/setup-texlive-action@v3.1.0
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
      - run: l3build check -q --show-log-on-error
