name: latexmk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yegor256/latexmk-action@0.5.0
        with:
          packages: xkeyval libertine minted fvextra catchfile xstring framed tcolorbox environ ffcode etoolbox
